# Generated by Django 5.2.4 on 2025-07-15 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 18, 1, 58, 489615, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
