# # Generated by Django 5.2.4 on 2025-07-22 16:31

from django.db import migrations
# from django.contrib.auth.models import Permission
# from django.contrib.contenttypes.models import ContentType


# content_type_global, created = ContentType.objects.get_or_create(app_label='users_app', model='global')

# def add_permissions(apps, schema_editor):

#     Permission.objects.create(
#         codename='can_manage_users',
#         name='Can manage users',
#         content_type=content_type_global
#     )

#     Permission.objects.create(
#         codename='can_add_permission_users',
#         name='Can add permission for users',
#         content_type=content_type_global
#     )

#     Permission.objects.create(
#         codename='can_access_user_list',
#         name='Can access user list',
#         content_type=content_type_global
#     )

# def rollback_permissions(apps, schema_editor):
#     Permission.objects.filter(
#         content_type=content_type_global,
#         codename__in=['can_manage_users', 'can_add_permission_users', 'can_access_user_list']
#     ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_todouser_date_joined'),
    ]

    operations = [
        # migrations.RunPython(
        #     code=add_permissions,
        #     reverse_code=rollback_permissions,
        # ),
    ]
