# Generated by Django 5.2.4 on 2025-08-01 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20250722_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 16, 54, 23, 63213, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
