# Generated by Django 5.2.4 on 2025-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_todouser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date joined'),
        ),
    ]
