name: Deploy app to Docker Hub

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Brunch to run the workwflow on'
                required: true
                default: 'main'

jobs:
   deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Chechkout code
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: |
                    ${{ secrets.DOCKER_HUB_USERNAME }}/todo_ninja:${{ github.sha }}
                    ${{ secrets.DOCKER_HUB_USERNAME }}/todo_ninja:latest
                build-args: |
                    BUILD_VERSION=${{ github.sha }}